import { emailValidator, firstNameValidator, lastNameValidator, loginValidator, passwordValidator, phoneValidator } from '@/services/Validator';

export const INPUT_FIELDS = [
  {
    id: 'email',
    name: 'email',
    value: 'pochta@yandex.ru',
    label: 'Почта',
    disabled: true,
    textError: '',
    validator: emailValidator,
  },
  {
    id: 'login',
    name: 'login',
    label: 'Логин',
    value: 'ivanivanov',
    disabled: true,
    validator: loginValidator,
  },
  {
    id: 'first_name',
    name: 'first_name',
    label: 'Имя',
    value: 'Иван',
    disabled: true,
    validator: firstNameValidator,
  },
  {
    id: 'second_name',
    name: 'second_name',
    label: 'Фамилия',
    value: 'Иванов',
    disabled: true,
    validator: lastNameValidator,
  },
  {
    id: 'display_name',
    name: 'display_name',
    label: 'Имя в чате',
    value: 'Иван',
    disabled: true,
    validator: lastNameValidator,
  },
  {
    id: 'phone',
    name: 'phone',
    label: 'Телефон',
    value: '+7 (909) 967 30 30',
    disabled: true,
    validator: phoneValidator,
  },
  {
    id: 'oldPassword',
    name: 'oldPassword',
    type: 'password',
    label: 'Старый пароль',
    value: 'test',
    disabled: true,
    autocomplete: false,
  },
  {
    id: 'newPassword',
    name: 'newPassword',
    type: 'password',
    label: 'Новый пароль',
    value: 'test',
    disabled: true,
    validator: passwordValidator,
    autocomplete: false,
  },
  {
    id: 'newPasswordRepeat',
    name: 'newPasswordRepeat',
    type: 'password',
    label: 'Повторите новый пароль',
    value: 'test',
    disabled: true,
    autocomplete: false,
    validator: () => '',
  },
];
